[tool.black]
line-length = 99
target-version = ['py35', 'py36', 'py37', 'py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "hug"
src_paths = ["djangocms_equation", "test"]
include_trailing_comma = true
line_length = 99
multi_line_output = 3
known_first_party = ["djangocms_equation"]
force_single_line = true

[tool.interrogate]
exclude = ["setup.py", "docs", "tests", ".eggs", "djangocms_equation\\migrations", "djangocms_equation/migrations"]
ignore-init-module = true
fail-under=100
verbose = 1
