# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquationPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_equation_equationpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('tex_code', models.CharField(blank=True, help_text='Insert you LaTeX code here.', max_length=256, verbose_name='tex_code')),
                ('filename', models.CharField(blank=True, default='', help_text='Optional. Enter the filename, if there are multiple files and you only want to display one.', max_length=32, verbose_name='filename')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
