# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_equation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equationpluginmodel',
            name='filename',
        ),
    ]
