# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_equation', '0002_remove_equationpluginmodel_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='equationpluginmodel',
            name='is_inline',
            field=models.BooleanField(default=0, help_text='Select if the equation should be inline.'),
        ),
    ]
