# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_equation', '0004_auto_20190405_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='equationpluginmodel',
            name='font_size_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('mm', 'mm'), ('in', 'in'), ('px *', 'px *'), ('pt', 'pt'), ('pc', 'pc'), ('em', 'em'), ('ex', 'ex'), ('ch', 'ch'), ('rem', 'rem'), ('vw', 'vw'), ('vh', 'vh'), ('vmin', 'vmin'), ('vmax', 'vmax'), ('%', '%')], default='rem', max_length=5, verbose_name='font_size_unit'),
        ),
        migrations.AddField(
            model_name='equationpluginmodel',
            name='font_size_value',
            field=models.FloatField(default=1, verbose_name='font_size_value'),
        ),
        migrations.AlterField(
            model_name='equationpluginmodel',
            name='is_inline',
            field=models.BooleanField(verbose_name='is_inline'),
        ),
        migrations.AlterField(
            model_name='equationpluginmodel',
            name='tex_code',
            field=models.CharField(blank=True, max_length=256, verbose_name='tex_code'),
        ),
    ]
