# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_equation', '0005_auto_20190406_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equationpluginmodel',
            name='font_size_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('mm', 'mm'), ('in', 'in'), ('px', 'px'), ('pt', 'pt'), ('pc', 'pc'), ('em', 'em'), ('ex', 'ex'), ('ch', 'ch'), ('rem', 'rem'), ('vw', 'vw'), ('vh', 'vh'), ('vmin', 'vmin'), ('vmax', 'vmax'), ('%', '%')], max_length=5, verbose_name='font_size_unit'),
        ),
    ]
