# Generated by Django 2.1.8 on 2019-04-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_equation', '0006_auto_20190424_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equationpluginmodel',
            name='is_inline',
            field=models.BooleanField(blank=True, verbose_name='is_inline'),
        ),
    ]
